services:
  app:
    build: ./
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    volumes:
      - .:/app # maps your local folder to container /app
      - /app/node_modules # prevents overwriting node_modules inside the container
  # example using image
  # db:
  #   image: mongo:4.0-xenial
  #   ports:
  #     - 27017:27017 #default port
